.TH APPSTACK "1" "July 2021" "AppStackJS 0.1.0" "User Commands"
.SH NAME
appstack \- AppStack Node.js Application controller.
.SH SYNOPSIS
.B appstack
[\fB\-h\fR|\fB\-\-help\fR]
[\fB\-\-version\fR]
.SH DESCRIPTION
AppStack is an extensive framework written for the Node.js framework.
This executable is how you launch your applications.

For more information, as well as an extensive list of AppStack's capabilities, go to https://appstackjs.github.io/.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Print a help message and exit.
.TP
.BR \-\-version
Print the version of the AppStack engine running as well as the AppStack bootloader version.
.SH REPORTING BUGS
AppStack is hosted in it's entirety on GitHub.
If you discover a bug in the code, please open an issue at https://github.com/appstackjs/<insert-package-name-here>/issues/.


